apiVersion: v1
kind: Namespace
metadata:
  name: reporting
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emma-report
  namespace: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emma-report
  template:
    metadata:
      labels:
        app: emma-report
    spec:
      containers:
      - name: emma-report
        image: luebken/emma-report-generator:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: emma-report-service
  namespace: reporting
spec:
  selector:
    app: emma-report
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP